alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias bc='bc -l'
alias c='clear'
alias l='ls -lah'
alias l.='ls -d .*'
alias h='history'
alias j='jobs -l'
alias ll='ls -lF'
alias la='ls -alF'
alias ff='find . -name $1'
alias mk='mkdir'
alias mkcd='_(){ mkdir -p $1; cd $1; }; _'
alias m='mvim .' 
alias ep='echo $PATH'
alias epp='echo -e ${PATH//:/\\n}'
alias eh='echo $HOME'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias gpr='grep -R'
alias gprl='grep -RL'
alias sha1='openssl sha1'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias svi='sudo vi'
alias vis='vim "+set si"'
alias edit='vim'
alias header='curl -I'
alias headerc='curl -I --compress'
alias root='sudo -i'
alias reboot='sudo /sbin/reboot'
alias poweroff='sudo /sbin/poweroff'
alias halt='sudo /sbin/halt'
alias shutdown='sudo /sbin/shutdown'