alias coba='cordova build android'
alias cobi='cordova build ios'
alias coea='cordova emulate android'
alias coei='cordova emulate ios'
alias cora='cordova run android --device'
alias cori='cordova run ios --device'